labels: ["enhancement", "idea"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for sharing your idea! Please provide as much detail as possible.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this idea solve?
      placeholder: Describe the problem or limitation you're experiencing...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like to see this solved?
      placeholder: Describe your proposed solution...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions?
      placeholder: Describe any alternative solutions you've thought about...
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any additional information, screenshots, or examples
      placeholder: Add any other context, mockups, or examples...
    validations:
      required: false
