labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for asking a question! Please provide as much context as possible to help us assist you.

  - type: textarea
    id: question
    attributes:
      label: Question
      description: What would you like to know?
      placeholder: Describe your question in detail...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: What are you trying to accomplish?
      placeholder: Provide context about what you're working on...
    validations:
      required: false

  - type: textarea
    id: attempted
    attributes:
      label: What I've Tried
      description: What have you already tried?
      placeholder: List the solutions you've already attempted...
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Your setup details
      placeholder: |
        - GitDocAI version:
        - OS:
        - Other relevant details:
    validations:
      required: false
